{"name": "test_add2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 4\n +  where 5 = add_number(2, 3)", "trace": "def test_add2():\n>       assert add_number(2, 3) == 4\nE       assert 5 == 4\nE        +  where 5 = add_number(2, 3)\n\ntest_allure.py:13: AssertionError"}, "start": 1635940442865, "stop": 1635940442865, "uuid": "d7b10c37-ca27-449b-b00a-044c29533325", "historyId": "f7cbd33b56b3642f66d2437ec14f056e", "testCaseId": "960977b090813bcad588a2f97b46148f", "fullName": "test_allure#test_add2", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "PC-20210828OZKE"}, {"name": "thread", "value": "3032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}